big_history_site/big_history_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('mapping_front.urls')),
    url(r'^admin/', admin.site.urls),
]

big_history_site/mapping_front/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # base url
    url(r'^$', views.index, name='index'),

    # grid view/via syllabus
    url(r'grid_view/(?P<learning_area_id>[0-9]+)/$', views.show_grid_view, name='show_grid_view'),

    # download grid view
    url(r'grid_view/(?P<learning_area_id>[0-9]+)/download$', views.download_grid_view, name='download_grid_view'),

    # big history view off main page
    # url(r'^big_history_view/$', views.big_hist_view, name='big_hist_view'),

    # show big history view of a subject
    url(r'^big_history_view/bh_unit/(?P<bh_unit_id>[0-9]+)/(?P<year_id>[0-9]+)/$', views.show_bh_unit, name='show_bh_unit'),

    # show syllabus view from main page
    # url(r'^syllabus_view/$', views.show_syllabus_view, name='show_syllabus_view'),

    ## START ADMIN ROUTES ##

    # admin area
    url(r'bh_admin/$', views.show_admin, name='show_admin'),

    # add learning area
    url(r'^bh_admin/add_learning_area', views.add_learning_area, name='add_learning_area'),
    #remove learning area
    url(r'^bh_admin/delete_learning_area/(?P<learning_area_id>[0-9]+)/$', views.delete_learning_area, name='delete_learning_area'),
    # edit learning area
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/$', views.edit_learning_area, name='edit_learning_area'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/(?P<parent_heading_id>[0-9]+)/add_point/$', views.add_point, name='add_point'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/(?P<parent_heading_id>[0-9]+)/add_subheading/$', views.add_subheading, name='add_subheading'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/add_heading/$', views.add_heading, name='add_heading'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/update_heading/(?P<heading_id>[0-9]+)$', views.update_heading, name='update_heading'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/update_subheading/(?P<subheading_id>[0-9]+)$', views.update_subheading, name='update_subheading'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/update_point/(?P<point_id>[0-9]+)$', views.update_point, name='update_point'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/remove_specific/(?P<ciric_specific_id>[0-9]+)/$', views.delete_ciric_specific, name='delete_ciric_specific'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/remove_subheading/(?P<heading_id>[0-9]+)/$', views.delete_ciric_subheading, name='delete_ciric_subheading'),
    url(r'^bh_admin/edit_learning_area/(?P<learning_area_id>[0-9]+)/remove_heading/(?P<heading_id>[0-9]+)/$', views.delete_ciric_heading, name='delete_ciric_heading'),

    # update ciric specific admin
    url(r'^bh_admin/ciric_specific/(?P<ciric_id>[0-9]+)/check/(?P<bh_id>[0-9]+)/$', views.check_bh, name='check_bh'),
    url(r'^bh_admin/ciric_specific/(?P<ciric_id>[0-9]+)/uncheck/(?P<bh_id>[0-9]+)/$', views.uncheck_bh, name='uncheck_bh'),

    # admin login page
    url(r'bh_admin/login', views.show_admin_login, name='bh_admin_login'),

    # admin login page
    url(r'bh_admin/logout', views.logout_view, name='bh_admin_logout'),

    ## END ADMIN ROUTES ##

    # json routes
    url(r'big_history/(?P<bh_unit_id>[0-9]+)/(?P<year_id>[0-9]+).json$', views.bh_unit_json, name='bh_unit_json')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

big_history_site/mapping_front/models.py
from django.db import models

class BigHistoryUnit(models.Model):
    unit_number = models.CharField(max_length=50)

    def __str__(self):
        return str(self.id) + ' ' + self.unit_number

class CiricLearningArea(models.Model):
    area_name = models.CharField(max_length=20)
    year = models.IntegerField(default=0)

    def __str__(self):
        return self.area_name + ' year ' + str(self.year) + ' ' + str(self.id)

class CiricLearningAreaHeading(models.Model):
    heading = models.CharField(max_length=200)
    learning_area = models.ForeignKey(CiricLearningArea)
    heading_type = models.CharField(max_length=4, default='SUBJ')

    def __str__(self):
        return self.learning_area.area_name + ': ' + self.heading

class CiricLearningAreaSubHeading(models.Model):
    heading = models.CharField(max_length=200)
    parent_heading = models.ForeignKey(CiricLearningAreaHeading, default=0)
    heading_type = models.CharField(max_length=4, default='CONT')

    def __str__(self):
        return self.parent_heading.learning_area.area_name + ' -> ' + self.parent_heading.heading + ': ' + self.heading

class CiricSpecific(models.Model):
    description = models.TextField(default='')
    parent_heading = models.ForeignKey(CiricLearningAreaSubHeading, default=0)
    code = models.CharField(max_length=20, blank=True, null=True)
    learning_area = models.ForeignKey(CiricLearningArea, default=0)

    def __str__(self):
        return self.parent_heading.heading + ' ' + self.code

    def big_history_units(self):
        return self.mapping_set.values_list('big_history', flat=True)

class Mapping(models.Model):
    big_history = models.ForeignKey(BigHistoryUnit)
    ciric_specific = models.ForeignKey(CiricSpecific)

    def __str__(self):
        return self.big_history.unit_number + ' maps to ' + self.ciric_specific.code

big_history_site/mapping_front/views.py
from django.http import HttpResponse, Http404, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django_xhtml2pdf.utils import generate_pdf

from .models import BigHistoryUnit, CiricLearningArea, CiricLearningAreaHeading, Mapping, CiricSpecific, CiricLearningAreaSubHeading

def index(request):
    return render(request, 'main_view.html')

def show_bh_unit(request, bh_unit_id, year_id):
    # try to find the bh unit
    try:
        bh_unit = BigHistoryUnit.objects.get(pk=bh_unit_id)
        learning_areas = CiricLearningArea.objects.filter(year=year_id).exclude(area_name="Cross Curriculum").exclude(area_name="General Capabilites")
        mappings = Mapping.objects.filter(big_history_id=bh_unit_id)
    except:
        raise Http404('Big History unit does not exist')

    # show bh circles
    return render(request, 'unit_view.html', { 'bh_unit': bh_unit, 'learning_areas': learning_areas, 'mappings': mappings, 'year': year_id })

def bh_unit_json(request, bh_unit_id, year_id):
    # grab those big history unit mappings
    mappings = Mapping.objects.filter(big_history_id=bh_unit_id)

    # setup placeholders
    return_data = {}

    # loop through mappings
    for mapping in mappings:
        # grab learning area
        learning_area = str(mapping.ciric_specific.learning_area_id)

        # check if we need to add new dict
        if learning_area not in return_data:
            # create new dict with base amounts
            return_data[learning_area] = { 'CONT': 0, 'CPTS': 0, 'ACHT': 0 }

        # grab amount of items
        amount = return_data[learning_area][mapping.ciric_specific.parent_heading.heading_type]

        # increment
        return_data[learning_area][mapping.ciric_specific.parent_heading.heading_type] = amount + 1


    # turn into usable json for d3
    data = { 'name': 'flare', 'color': '#2e2e2e', 'children': [] }

    # add children
    for learning_area in CiricLearningArea.objects.filter(year=year_id).exclude(area_name='Cross Curriculum').exclude(area_name='General Capabilites'):
        # create area to append
        to_append = {
            'name': learning_area.area_name,
            'color': '#474747',
            'link': learning_area.id,
            'children': [
                {
                    'name': 'Achievement',
                    'type': 'ACHT',
                    'color': '#616161',
                    'link': learning_area.id,
                    'children': []
                },
                {
                    'name': 'Content',
                    'type': 'CONT',
                    'color': '#616161',
                    'link': learning_area.id,
                    'children': []
                },
                {
                    'name': 'Concepts',
                    'type': 'CPTS',
                    'color': '#616161',
                    'link': learning_area.id,
                    'children': []
                },
            ]
        }

        # add number of children
        for key, area in enumerate(to_append['children']):
            # check if exists
            if str(learning_area.id) in return_data:
                # work out how many nodes
                nodes = return_data[str(learning_area.id)][area['type']]

                # loop and add nodes
                for i in range(nodes):
                    to_append['children'][key]['children'].append({ 'name': '', 'color': '#7a7a7a' })

        # append
        data['children'].append(to_append)



    # return as json
    return JsonResponse(data, safe=False)

def show_grid_view(request, learning_area_id):
    # try find the learning area and headings to go along with it
    try:
        learning_areas = CiricLearningArea.objects.order_by('id')
        learning_area = CiricLearningArea.objects.get(pk=learning_area_id)
        headings1 = learning_area.ciriclearningareaheading_set.filter(heading='Concepts')
        headings2 = learning_area.ciriclearningareaheading_set.exclude(heading='Concepts')
        headings = headings1 | headings2
    except CiricLearningArea.DoesNotExist:
        raise Http404('Learning area does not exist')

    return render(request, 'grid_view.html', { 'learning_area': learning_area, 'headings': headings,'learning_areas':learning_areas, 'bh': range(1, 11) })

# old views for seperate big hist, curric view
#def big_hist_view(request):
#    return render(request, "big_history_view.html")
#def show_syllabus_view(request):
#    return render(request, 'syllabus_view.html')

def download_grid_view(request, learning_area_id):
    # begin response
    resp = HttpResponse(content_type='application/pdf')

    # create context
    context = {}

    # try find the learning area and headings to go along with it
    try:
        context['learning_area'] = CiricLearningArea.objects.get(pk=learning_area_id)
        context['headings'] = context['learning_area'].ciriclearningareaheading_set.all()
    except CiricLearningArea.DoesNotExist:
        raise Http404('Learning area does not exist')

    # show grid view response
    context['bh'] = range(1, 11)

    # create result
    result = generate_pdf('pdf_grid_view.html', file_object=resp, context=context)

    # return result
    return result
    # return render(request, 'grid_view.html', { 'learning_area': learning_area, 'headings': headings,'learning_areas':learning_areas, 'bh': range(1, 11) })

def show_admin_login(request):
    #check if already logged in
    if request.user.is_authenticated():
        return redirect('show_admin')

    if request.method == 'GET':
        return render(request, "bh_admin/login_view.html")
    elif request.method == 'POST':
        # grab username and password
        username_inp = request.POST.get('username', '')
        password_inp = request.POST.get('password', '')

        # try authenticate
        user = authenticate(username=username_inp, password=password_inp)

        #check if it works, if so then login
        if user is not None:
            login(request, user)

            # take user on
            return redirect('show_admin')
        else:
            return render(request, "bh_admin/login_view.html")

def logout_view(request):
    logout(request)

    # redirect to login page
    return redirect('bh_admin_login')

@login_required(login_url='bh_admin/login')
def show_admin(request):
    # grab learning areas for each year
    nine_areas = CiricLearningArea.objects.filter(year=9).order_by('area_name')
    ten_areas = CiricLearningArea.objects.filter(year=10).order_by('area_name')

    # return template
    return render(request, 'bh_admin/admin_view.html', { 'nine': nine_areas, 'ten': ten_areas })

@login_required(login_url='bh_admin/login')
def add_learning_area(request):
    # grab details from request
    year = request.POST.get('year')
    area = request.POST.get('new_area')

    # create new learning area
    learning_area = CiricLearningArea(year=year, area_name=area)

    # save
    learning_area.save()

    # send back to admin
    return redirect('show_admin')

@login_required(login_url='bh_admin/login')
def edit_learning_area(request, learning_area_id):
    # try find the learning area and headings to go along with it
    try:
        learning_area = CiricLearningArea.objects.get(pk=learning_area_id)
        headings = learning_area.ciriclearningareaheading_set.all()
    except CiricLearningArea.DoesNotExist:
        raise Http404('Learning area does not exist')

    # show grid view response
    return render(request, 'edit_grid_view.html', { 'learning_area': learning_area, 'headings': headings, 'bh': range(1, 11)})

@login_required(login_url='bh_admin/login')
def check_bh(request, ciric_id, bh_id):
    # create new mapping
    mapping = Mapping(big_history_id=bh_id, ciric_specific_id=ciric_id)

    # commit to model by saving
    mapping.save()

    # return added response
    return HttpResponse('added')

@login_required(login_url='bh_admin/login')
def uncheck_bh(request, ciric_id, bh_id):
    # try find the mapping model if it exists
    try:
        # grab model and delete if exits
        mapping = Mapping.objects.get(big_history_id=bh_id, ciric_specific_id=ciric_id)
        mapping.delete()
    except Mapping.DoesNotExist:
        # 404 not found if no model
        raise Http404('Uh oh!')

    # deleted response
    return HttpResponse('deleted')

@login_required(login_url='bh_admin/login')
def delete_learning_area(request, learning_area_id):
    # try find model
    try:
        learning_area = CiricLearningArea.objects.get(id=learning_area_id)
        learning_area.delete()
    except CiricLearningArea.DoesNotExist:
        raise Http404('could not delete learning area')

    # send back to admin
    return redirect('show_admin')

@login_required(login_url='bh_admin/login')
def add_point(request, learning_area_id, parent_heading_id):
    # check for post method
    if request.method == 'POST':
        # grab the variables
        desc = request.POST.get('desc', '')
        code = request.POST.get('code', '')

        # create new cirric specific
        ciric_specific = CiricSpecific(description=desc, code=code, parent_heading_id=parent_heading_id)

        # save the item to db
        ciric_specific.save()

        # redirect
        return redirect('edit_learning_area', learning_area_id=learning_area_id)
    elif request.method == 'GET':
        raise Http404('Uh oh!')

@login_required(login_url='bh_admin/login')
def add_subheading(request, learning_area_id, parent_heading_id):
    # check for post method
    if request.method == 'POST':
        # grab the variables
        sub = request.POST.get('sub_heading', '')

        # create new subheading
        sub_heading = CiricLearningAreaSubHeading(heading=sub, parent_heading_id=parent_heading_id)

        # save the item to db

big_history_site/mapping_front/templates/base.html
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8" >
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}" >
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:700,300" rel="stylesheet" type="text/css">
  <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <script src="https://code.jquery.com/jquery-1.12.3.min.js" ></script>
  <title>{% block title %}Big History{% endblock %}</title>
</head>

<body>
  {% block pageWrapper %}
  <div id="pageWrapper">
    <div id="banner">
    {% block banner %}
    <div id="logo">
      {% block logo %}
        <a href="{% url 'index' %}"><img src="{% static "images/MQ_Big_History_Horizontal_RGB.png" %}" alt="Home" width="50%" height"50%"></a>
      {% endblock %}
    </div>
    {% endblock %}
    </div>
    <div class="page">
        {% block content %}

        {% endblock %}
    </div>
    {% endblock %}
  </div>
</body>
</html>

big_history_site/mapping_front/templates/edit_grid_view.html
{% load staticfiles %}
<!doctype html>
<html lang="en" >
<head>
  <meta charset="utf-8" >
  <title>Editing {{ learning_area.area_name }}</title>
  <link rel="stylesheet" type="text/css" href="{% static "css/edit_grid_view.css" %}" >
</head>

<body>

  <div class="top" >
    <h1>Updating Year {{ learning_area.year }} Learning Area: {{ learning_area.area_name }}</h1>
  </div>

  <table class="larea" width="100%" cellpadding="5" cellspacing="0" >
    <thead>
      <tr>
        <th colspan="1" width="40%" >Learning Outcomes</th>
        <th colspan="10" >Big History (Units)</th>
      </tr>

      <tr class="units" >
        <th></th>
        <th class="unit1" >1</th>
        <th class="unit2" >2</th>
        <th class="unit3" >3</th>
        <th class="unit4" >4</th>
        <th class="unit5" >5</th>
        <th class="unit6" >6</th>
        <th class="unit7" >7</th>
        <th class="unit8" >8</th>
        <th class="unit9" >9</th>
        <th class="unit10" >10</th>
      </tr>
    </thead>

    <tbody>
      {% for heading in headings %}
      <tr>
        <td class="heading" id="heading{{ heading.id }}" >
          Heading: <input type="text" uid="{{ heading.id }}" name="heading" class="heading_inp inp" value="{{ heading.heading }}" >
          <a class="del" href="{% url 'delete_ciric_heading' learning_area.id heading.id %}" onclick="return confirm('Are you sure you want to delete this heading? It will delete all subheadings and points underneath it');" >X
          </a>
        </td>
      </tr>

      {% for sub_heading in heading.ciriclearningareasubheading_set.all %}
      <tr>
        <td class="sub_heading" id="subheading{{ sub_heading.id }}" >Sub Heading: <input type="text" uid="{{ sub_heading.id }}" name="sub_heading" class="subheading_inp inp" value="{{ sub_heading.heading }}" ><a class="del" href="{% url 'delete_ciric_subheading' learning_area.id sub_heading.id %}" onclick="return confirm('Are you sure you want to delete this subheading? It will delete all points underneath it and cannot be undone');" >X</a></td>
      </tr>

      {% for ciric_specific in sub_heading.ciricspecific_set.all %}
      <tr class="ld" >
        <td class="desc" id="point{{ ciric_specific.id }}" >
          Point:
          <textarea class="ciricdesc_inp inp" uid="{{ ciric_specific.id }}" >{{ ciric_specific.description }}</textarea>
          {% if sub_heading.heading != 'Concepts' and sub_heading.heading != 'Achievements' %}
          Code:
          <input class="ciriccode_inp inp" uid="{{ ciric_specific.id }}" name="code" value="{{ ciric_specific.code }}" >
          {% endif %}
          <a class="del" href="{% url 'delete_ciric_specific' learning_area.id ciric_specific.id %}" onclick="return confirm('Are you sure you want to delete this point? This cannot be undone');" >X</a>
        </td>

        {% for i in bh %}
        <td align="center" ><input type="checkbox" class="bh_checkbox" unit="{{ i }}" ciric_specific="{{ ciric_specific.id }}" {% if i in ciric_specific.big_history_units %}checked{% endif %}></td>
        {% endfor %}
      </tr>
      {% endfor %}
      <tr class="ld" >
        <td class="desc addp" colspan="11" >
          <form method="post" action="{% url 'add_point' learning_area.id sub_heading.id %}" >
            {% csrf_token %}
            <textarea onclick="this.value='';" name="desc" >Curriculum point description</textarea><br />
            <input type="text" name="code" value="Code" onclick="this.value='';" >
            <input type="submit" name="sub" value="Add Point" >
          </form>
        </td>
      </tr>
      {% endfor %}
      <tr>
        <td class="sub_heading addp" colspan="11" >
          <form method="post" action="{% url 'add_subheading' learning_area.id heading.id %}" >
            {% csrf_token %}
            <input type="text" name="sub_heading" value="Subheading" onclick="this.value='';" >
            <input type="submit" name="sub" value="Add Subheading" >
          </form>
        </td>
      </tr>
      {% endfor %}
      <tr>
        <td class="heading addp" colspan="11" >
          <form method="post" action="{% url 'add_heading' learning_area.id %}" >
            {% csrf_token %}
            <input type="text" name="heading" value="Heading" onclick="this.value='';" >
            <input type="submit" name="sub" value="Add Heading" >
          </form>
        </td>
      </tr>
    </tbody>
  </table>

  <script src="https://code.jquery.com/jquery-1.12.3.min.js" ></script>
  <script type="text/javascript" >

  $(document).ready(function() {
    $('.bh_checkbox').change(function() {
      // grab info for relationship
      var unit_id = $(this).attr('unit');
      var ciric_id = $(this).attr('ciric_specific');

      // create url
      var url = 'http://localhost:8000/bh_admin/ciric_specific/' + ciric_id + (($(this).is(':checked')) ? '/check/' : '/uncheck/') + unit_id;

      // make get request
      $.get(url, function(data) {
        console.log(data);
      });
    });

    $('.heading_inp').keyup(function() {
      // fields
      var heading = $(this).val();
      var id = $(this).attr('uid');

      // create url
      var url = 'http://localhost:8000/bh_admin/edit_learning_area/{{ learning_area.id }}/update_heading/' + id;

      // update field
      $.post(url, { heading: heading, csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value }, function(response) {
        console.log(response);
      });
    });

    $('.subheading_inp').keyup(function() {
      // fields
      var heading = $(this).val();
      var id = $(this).attr('uid');

      // create url
      var url = 'http://localhost:8000/bh_admin/edit_learning_area/{{ learning_area.id }}/update_subheading/' + id;

      // update field
      $.post(url, { heading: heading, csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value }, function(response) {
        console.log(response);
      });
    });

    $('.ciricdesc_inp').keyup(function() {
      // fields
      var point = $(this).val();
      var id = $(this).attr('uid');

      // create url
      var url = 'http://localhost:8000/bh_admin/edit_learning_area/{{ learning_area.id }}/update_point/' + id;

      // update field
      $.post(url, { point: point, csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value }, function(response) {
        console.log(response);
      });
    });

    $('.ciriccode_inp').keyup(function() {
      // fields
      var code = $(this).val();
      var id = $(this).attr('uid');

      // create url
      var url = 'http://localhost:8000/bh_admin/edit_learning_area/{{ learning_area.id }}/update_point/' + id;

      // update field
      $.post(url, { code: code, csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value }, function(response) {
        console.log(response);
      });
    });
  });

  </script>
</body>
</html>

big_history_site/mapping_front/templates/grid_view.html
{% extends "base.html" %}
{% load staticfiles%}

{% block title %}{{ learning_area.area_name }}{% endblock %}
  {% block content %}
{% block dropbox %}
<div id="dropbox">
  <div id="drop-box-text" onclick="dropDown()">
    <p class="unselectable">Select Learning Area</p>
  </div>
  <div id="dropbox-content" class="dropdown-content">
    <ul>
      {% for lA in learning_areas %}
      <a href="{% url 'show_grid_view' learning_area_id=lA.id %}"/>
      <li>
        <p>{{lA.area_name}} Year {{lA.year}}</p>
      </li>
      </a>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}
  <script type="text/javascript">
  function dropDown(){
    document.getElementById("dropbox-content").classList.toggle("show");
  }

  window.onclick = function(event) {
    if (!event.target.matches('#drop-box-text')) {

      var dropdowns = document.getElementsByClassName("dropdown-content");
      var i;
      for (i = 0; i < dropdowns.length; i++) {
        var openDropdown = dropdowns[i];
        if (openDropdown.classList.contains('show')) {
            openDropdown.classList.remove('show');
        }
      }
    }
  }

  $(document).ready(function() {
    var lastThis;
    var hidden;
    $('.hidden_section').hide()
    $('.heading').click(function() {
      $('.hidden_section').stop().hide();
      if(lastThis != this){
        $(this).parent().nextUntil('.next').stop().show();
        $(this).parent().nextUntil('.next').children().stop().show();
        lastThis = this;
      }else{
        $(this).parent().nextUntil('.next').stop().hide();
        $(this).parent().nextUntil('.next').children().stop().hide();
        lastThis = undefined;
      }
    });
  });
  </script>
    <div class="top" >
      <h1>Learning Area: {{ learning_area.area_name }} Year {{learning_area.year}}(<a href="{% url 'download_grid_view' learning_area.id %}" target="_blank" >download pdf</a>)</h1>
    </div>

    <table class="larea" width="100%" cellpadding="5" cellspacing="0" >
      <thead>
        <tr>
          <th colspan="1" width="40%" >Learning Outcomes</th>
          <th colspan="10" >Big History (Units)</th>
        </tr>
        <tr class="units" >
          <th></th>
          <th class="unit1">1</th>
          <th class="unit2">2</th>
          <th class="unit3">3</th>
          <th class="unit4">4</th>
          <th class="unit5">5</th>
          <th class="unit6">6</th>
          <th class="unit8">8</th>
          <th class="unit7">7</th>
          <th class="unit9">9</th>
          <th class="unit10">10</th>
        </tr>
      </thead>

      <tbody>
        {% for heading in headings %}
        <tr class="next">
          <td class="heading" >{{ heading.heading }}{% if heading.heading.lower != 'concepts' and heading.heading.lower != 'achievements' %} ({{ heading.ciriclearningareasubheading_set.all|length }}){% else %}...{% endif %}</td>
        </tr>
        {% for sub_heading in heading.ciriclearningareasubheading_set.all %}
        {% if sub_heading.heading.lower != heading.heading.lower %}
        <tr class="hidden_section">
          <td class="sub_heading" >{{ sub_heading.heading }}</td>
        </tr>
        {% endif %}

        {% for ciric_specific in sub_heading.ciricspecific_set.all %}
        <tr class="ld hidden_section">
          <td class="desc" >
            {{ ciric_specific.description }}
            {% if sub_heading.heading.lower != 'concepts' and sub_heading.heading.lower != 'achievements' %}
              ({{ ciric_specific.code }})
            {% endif %}
          </td>

          {% for i in bh %}
          <td align="center" class="tick">
            <p>{% if i in ciric_specific.big_history_units %}✔{% endif %}</p>
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
        {% endfor %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

big_history_site/mapping_front/templates/pdf_grid_view.html
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8" >
    <title>{{ learning_area.area_name }} - Year {{ learning_area.year }}</title>
    <style type="text/css" >



    </style>
</head>

<body>

    <table class="larea" width="100%" cellpadding="5" cellspacing="0" border="1" >
      <thead>
        <tr>
          <th colspan="1" width="50%" >Learning Outcomes</th>
          <th colspan="10" >Big History (Units)</th>
        </tr>

        <tr class="units" >
          <th></th>
          <th class="unit1" >1</th>
          <th class="unit2" >2</th>
          <th class="unit3" >3</th>
          <th class="unit4" >4</th>
          <th class="unit5" >5</th>
          <th class="unit6" >6</th>
          <th class="unit7" >7</th>
          <th class="unit8" >8</th>
          <th class="unit9" >9</th>
          <th class="unit10" >10</th>
        </tr>
      </thead>

      <tbody>
        {% for heading in headings %}
        <tr>
          <td class="heading" id="heading{{ heading.id }}" colspan="11" >
            {{ heading.heading }}
          </td>
        </tr>

        {% for sub_heading in heading.ciriclearningareasubheading_set.all %}
        <tr>
          <td class="sub_heading" id="subheading{{ sub_heading.id }}" colspan="11" >
              {{ sub_heading.heading }}
          </td>
        </tr>

        {% for ciric_specific in sub_heading.ciricspecific_set.all %}
        <tr class="ld" >
          <td class="desc" id="point{{ ciric_specific.id }}" width="100%" >
            {{ ciric_specific.description }}
            {% if sub_heading.heading != 'Concepts' and sub_heading.heading != 'Achievements' %}
            ({{ ciric_specific.code }})
            {% endif %}
          </td>

          {% for i in bh %}
          <td align="center" >
              {% if i in ciric_specific.big_history_units %}&#10003;{% endif %}
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
        {% endfor %}
        {% endfor %}
      </tbody>
    </table>

</body>
</html>